#!/usr/bin/env python3
"""Generate crates/pericynthion/src/jpl/oracle_data.rs from a b3sum manifest.
Usage: gen_oracle.py <manifest> <nasa_root> > oracle_data.rs
Manifest lines: "<hex>  <relpath-from-nasa_root>"."""
import os, sys, collections

manifest, nasa_root = sys.argv[1], sys.argv[2]
dirs = collections.OrderedDict()
for line in open(manifest, encoding="utf-8"):
    line = line.rstrip("\n")
    if not line:
        continue
    h, rel = line.split("  ", 1)
    d, name = os.path.split(rel)
    size = os.path.getsize(os.path.join(nasa_root, rel))
    dirs.setdefault(d, []).append((name, size, h))

out = []
out.append("//! GENERATED by scripts/gen_oracle.py — DO NOT EDIT BY HAND.")
out.append("//! Source mirror: ssd.jpl.nasa.gov/ftp/eph/{planets,satellites,small_bodies}/")
out.append("#![allow(clippy::unreadable_literal, clippy::doc_markdown)]\n")
out.append("use super::{OracleDir, OracleFile};\n")
out.append("pub(crate) static DIRS: &[OracleDir] = &[")
for d, files in dirs.items():
    out.append(f'    OracleDir {{ prefix: "{d}", files: &[')
    for name, size, h in files:
        out.append(f'        OracleFile {{ name: "{name}", size: {size}, blake3_hex: "{h}" }},')
    out.append("    ] },")
out.append("];")
print("\n".join(out))
