#!/usr/bin/env python3
"""Generate crates/pericynthion/src/jpl/oracle_data.rs from a sized manifest.
Usage: gen_oracle.py <manifest.tsv> > oracle_data.rs
Manifest lines (tab-separated): "<prefix>\t<name>\t<size>\t<blake3hex>".
Deterministic: directory order = first-seen in the manifest; files keep
manifest order within a directory.

IMPORTANT — formatting requirement:
The committed oracle_data.rs is the generate-then-`cargo fmt` fixed point.
After regenerating, you MUST run `cargo fmt -p pericynthion`; the raw
generator output is not rustfmt-clean on its own.  The justfile recipe
`just oracle-regen` does both steps in one command and is the recommended
way to regenerate the file."""
import collections, sys

# Directory prefix -> SourceKind. Default JplMirror.
KIND_BY_PREFIX = {
    "cdsarc.cds.unistra.fr/ftp/cats/V/50": "CdsCatalog",
}

# DE441 carries the lights, the major planets, and Pluto.
DE441_PROVIDES = [
    "Sun", "Moon", "Mercury", "Venus", "Mars", "Jupiter",
    "Saturn", "Uranus", "Neptune", "Pluto",
]
# Filename -> (provides list, coverage gloss-or-None). Files absent here get
# `provides: &[]`, `coverage: None`.
COVERAGE_BY_NAME = {
    "linux_m13000p17000.441": (DE441_PROVIDES, "DE441 (-13200 .. +17191)"),
    "sb441-n16.bsp": (["Ceres", "Pallas", "Juno", "Vesta", "Hygiea"], None),
    "sb441-n373.bsp": (
        ["Eris", "Haumea", "Makemake", "Quaoar", "Orcus",
         "Ixion", "Varuna", "Sedna", "Gonggong"],
        None,
    ),
    "catalog.gz": (["@fixed-stars"], "Yale BSC5P (Hoffleit & Warren 1991)"),
}

def rust_provides(names):
    if not names:
        return "&[]"
    inner = ", ".join(f'"{n}"' for n in names)
    return f"&[{inner}]"

def rust_coverage(cov):
    return "None" if cov is None else f'Some("{cov}")'

dirs = collections.OrderedDict()
for line in open(sys.argv[1], encoding="utf-8"):
    line = line.rstrip("\n")
    if not line:
        continue
    prefix, name, size, h = line.split("\t")
    dirs.setdefault(prefix, []).append((name, int(size), h))

out = []
out.append("//! GENERATED by scripts/gen_oracle.py — DO NOT EDIT BY HAND.")
out.append("//! Source: scripts/oracle_manifest.tsv")
out.append("//! Families: ssd.jpl.nasa.gov/ftp/eph/{planets,satellites,small_bodies}/ ; cdsarc.cds.unistra.fr/ftp/cats/V/50/")
out.append("#![allow(clippy::unreadable_literal, clippy::doc_markdown)]\n")
out.append("use super::{OracleDir, OracleFile, SourceKind};\n")
out.append("pub(crate) static DIRS: &[OracleDir] = &[")
for prefix, files in dirs.items():
    kind = KIND_BY_PREFIX.get(prefix, "JplMirror")
    out.append(f'    OracleDir {{ prefix: "{prefix}", kind: SourceKind::{kind}, files: &[')
    for name, size, h in files:
        prov, cov = COVERAGE_BY_NAME.get(name, ([], None))
        out.append(
            f'        OracleFile {{ name: "{name}", size: {size}, '
            f'blake3_hex: "{h}", provides: {rust_provides(prov)}, '
            f'coverage: {rust_coverage(cov)} }},'
        )
    out.append("    ] },")
out.append("];")
print("\n".join(out))
